### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by ninokierulf** [ninokierulf/hexagon#2]
As a developer, one should be able to trigger automated tasks
- building
- testing
- publishing

Github Actions seems like a good candidate for codes hosted in Github

## Tasks
- [x] Branch protection on `main`
- [x] Integration workflow (build passing, unit tests passing)
- [ ] Store action secrets into github. [link](https://github.com/ninokierulf/hexagon/settings/secrets/actions)
- [ ] Release workflow (generate ipa and deploy to: AppCenter, Apple AppstoreConnect)

## References

- [Github Actions Documentation](https://docs.github.com/en/actions)
